language: scala
sudo: false

scala:
  - 2.11.8
    #  - 2.12.1 # https://issues.scala-lang.org/browse/SI-10168

jdk:
  - oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom source-map-support

env:
  global:
    JSENV=node

script:
  # - sbt ++$TRAVIS_SCALA_VERSION test/test:fastOptJS test/test:fullOptJS
  # - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
  # - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' 'set scalaJSStage in ThisBuild := FullOptStage' test
  # - bin/checkDevOnly $TRAVIS_SCALA_VERSION
  - sbt ++$TRAVIS_SCALA_VERSION neo/test:fastOptJS neo/test:fullOptJS
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' neo/test
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' 'set scalaJSStage in ThisBuild := FullOptStage' neo/test

# Taken from https://github.com/typelevel/cats/blob/master/.travis.yml
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache

